server:
  port: 9999

spring:
  application:
    name: zuul-proxy
    
eureka:
  client:
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:8761/eureka

zuul: 
  prefix: /app
  routes: 
    by-client: 
      location: hr-service
      path: /services/**
    by-direct: 
      location: "http://localhost:8081"
      path: /proxy/**
    by-service: 
      location: emp-service
      path: /services/**
    test-redirect: 
      location: "http://www.google.com"
      path: /redirect/** 